# Generated by Django 5.0.7 on 2024-07-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalSupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.SmallIntegerField()),
                ('mes', models.SmallIntegerField()),
                ('entidad_RS', models.CharField(max_length=100)),
                ('puc_codigo', models.CharField(max_length=128)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bal_sup',
                'ordering': ['-created_at'],
            },
        ),
    ]
