# Generated by Django 5.0.7 on 2024-07-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balSup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balsupmodel',
            name='entidad_RS',
            field=models.CharField(max_length=128),
        ),
    ]
