# Generated by Django 5.0.7 on 2024-07-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balCoop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balcoopmodel',
            name='entidad_nit',
            field=models.CharField(max_length=128),
        ),
    ]
