# Generated by Django 5.0.7 on 2024-07-18 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balCoop', '0008_rename_entidad_nit_balcoopmodel_entidad_rs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balcoopmodel',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='balcoopmodel',
            name='entidad_RS',
            field=models.CharField(max_length=128),
        ),
    ]
