# Generated by Django 5.0.7 on 2025-03-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balCoop', '0009_alter_balcoopmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balcoopmodel',
            name='entidad_RS',
            field=models.CharField(max_length=150),
        ),
    ]
