# Generated by Django 5.2 on 2025-06-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entidad', '0002_alter_entidadmodel_dv_alter_entidadmodel_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidadmodel',
            name='Gremio',
        ),
    ]
