# Generated by Django 4.2.6 on 2023-10-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucCoop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccoopmodel',
            name='Agrupa',
            field=models.CharField(default=True, max_length=10, null=True),
        ),
    ]
