# Generated by Django 5.0.7 on 2025-01-15 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pucCoop', '0002_alter_puccoopmodel_agrupa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puccoopmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='puccoopmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
