# Generated by Django 5.2 on 2025-06-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidad', '0003_remove_entidadmodel_gremio'),
    ]

    operations = [
        migrations.CreateModel(
            name='GremioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'gremios',
                'db_table': 'gremio',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='GremioToEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gremio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gremio_to_entity', to='gremio.gremiomodel')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gremio_to_entity', to='entidad.entidadmodel')),
            ],
            options={
                'db_table': 'gremio_to_entity',
                'unique_together': {('Gremio', 'entidad')},
            },
        ),
    ]
