# Generated by Django 5.2 on 2025-06-24 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gremio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gremiomodel',
            options={'ordering': ['id'], 'verbose_name_plural': 'gremios'},
        ),
    ]
