# Generated by Django 4.2.6 on 2023-10-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PucSupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.CharField(max_length=128)),
                ('Descripcion', models.CharField(max_length=300)),
                ('Agrupa', models.CharField(default=True, max_length=10, null=True)),
                ('CreditoRiesgo', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'puc_sup',
                'ordering': ['-created_at'],
            },
        ),
    ]
