# Generated by Django 5.0.7 on 2024-09-09 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pucSup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pucsupmodel',
            options={'ordering': ['Codigo']},
        ),
    ]
