# Generated by Django 5.0.7 on 2025-02-13 15:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_alter_user_username'),
        ('entidad', '0002_alter_entidadmodel_dv_alter_entidadmodel_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_vinculacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_entidades', to='entidad.entidadmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_entidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_entidad',
                'unique_together': {('user', 'entidad')},
            },
        ),
    ]
