# Generated by Django 5.2 on 2025-06-24 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0007_alter_user_email_alter_user_updated_at'),
        ('gremio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gremio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gremio.gremiomodel'),
        ),
    ]
