# Generated by Django 5.2 on 2025-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0008_user_gremio'),
        ('gremio', '0002_alter_gremiomodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gremio',
        ),
        migrations.AddField(
            model_name='user',
            name='gremios',
            field=models.ManyToManyField(blank=True, related_name='users', to='gremio.gremiomodel'),
        ),
    ]
